"""
Article 2: Modeling Permeability in Different Carbonate Rock Types
Dernaika, Masalmeh, Mansour, Al Jallad, Koronfol (2023)
DOI: 10.30632/PJV64N1-2023a2

Implements the three classical phi-k models compared in the paper and fits
them per carbonate rock type (RRT 1 grainy, RRT 2 mixed, RRT 3 muddy):

  (i)   Amaefule flow zone indicator (Eqs. 1-3)
  (ii)  Lucia rock-fabric number       (Eqs. 4-5)
  (iii) Winland-Kolodzie r35           (Eq. 6)

Synthetic data are drawn from three log-linear phi-k trends approximating the
limestone trends reported in the paper (mean FZI 3.5 / 0.9 / 0.35 micron and
mean RFN 1.7 / 2.85 / 3.65).
"""

import numpy as np


# -------------------------------------------------- Amaefule FZI (Eqs 1-3) ---

def rqi(k_md, phi):
    """Reservoir Quality Index, micron.  RQI = 0.0314 * sqrt(k / phi)  (Eq. 1)."""
    return 0.0314 * np.sqrt(k_md / phi)


def npi(phi):
    """Normalised Porosity Index.  NPI = phi / (1 - phi)  (Eq. 2)."""
    return phi / (1.0 - phi)


def fzi(k_md, phi):
    """Flow Zone Indicator, micron.  FZI = RQI / NPI  (Eq. 3)."""
    return rqi(k_md, phi) / npi(phi)


def k_from_fzi(phi, fzi_mean):
    """Invert Eqs. 1-3 for k given mean FZI and porosity."""
    return 1014.0 * (fzi_mean ** 2) * (phi ** 3) / (1.0 - phi) ** 2


# ---------------------------------------------- Lucia rock-fabric number ---

def lucia_rfn_from_swi(phi_g, swi):
    """Lucia RFN from interparticle porosity and irreducible water saturation (Eq. 4).

        log(RFN) = (3.1107 + 1.8834 * log phi_g + log Swi) /
                   (3.0634 + 1.4045 * log phi_g)
    """
    num = 3.1107 + 1.8834 * np.log10(phi_g) + np.log10(swi)
    den = 3.0634 + 1.4045 * np.log10(phi_g)
    return 10.0 ** (num / den)


def lucia_k(phi_g, rfn):
    """Lucia permeability prediction (Eq. 5).

        log k = (9.7982 - 12.0838 log RFN) + (8.6711 - 8.2965 log RFN) log phi_g
    """
    a = 9.7982 - 12.0838 * np.log10(rfn)
    b = 8.6711 - 8.2965 * np.log10(rfn)
    return 10.0 ** (a + b * np.log10(phi_g))


# ---------------------------------------------- Winland-Kolodzie r35 (Eq 6) ---

def winland_r35(k_md, phi):
    """Pore-throat radius at 35% Hg saturation, micron.

        log r35 = 0.732 + 0.588 log k - 0.864 log phi   (Eq. 6)
    """
    return 10.0 ** (0.732 + 0.588 * np.log10(k_md) - 0.864 * np.log10(phi * 100.0))


def winland_k(phi, r35):
    """Invert Eq. 6 for permeability given r35 and porosity."""
    return 10.0 ** ((np.log10(r35) - 0.732 + 0.864 * np.log10(phi * 100.0)) / 0.588)


# --------------------------------------------------------- synthetic dataset --

RRT = {
    # FZI / RFN values are the paper's Table-2 per-rock-type averages
    "grainy": dict(fzi_mean=3.50, rfn=1.70, phi_lo=0.10, phi_hi=0.33, swi=0.10),
    "mixed":  dict(fzi_mean=0.90, rfn=2.85, phi_lo=0.06, phi_hi=0.25, swi=0.25),
    "muddy":  dict(fzi_mean=0.35, rfn=3.65, phi_lo=0.05, phi_hi=0.22, swi=0.45),
}


def make_carbonate_dataset(n_per_class=120, log_sigma=0.25, seed=0):
    """Return phi, k_md, rrt arrays drawn from three FZI-consistent trends.

    Permeability is generated by inverting Eqs. 1-3 with the per-class
    target FZI, then perturbed with log-Gaussian noise to mimic measurement
    + heterogeneity scatter.
    """
    rng = np.random.default_rng(seed)
    phi_all, k_all, rrt_all = [], [], []
    for name, p in RRT.items():
        phi = rng.uniform(p["phi_lo"], p["phi_hi"], n_per_class)
        k_clean = k_from_fzi(phi, p["fzi_mean"])
        k = k_clean * 10.0 ** rng.normal(0.0, log_sigma, n_per_class)
        phi_all.append(phi)
        k_all.append(k)
        rrt_all.extend([name] * n_per_class)
    return (np.concatenate(phi_all), np.concatenate(k_all), np.array(rrt_all))


# ------------------------------------------------------------------ tests ---

def factor_within(predicted, actual, factor=2.0):
    """Fraction of samples for which |log10(pred/actual)| <= log10(factor)."""
    ratio = np.log10(np.maximum(predicted, 1e-9) / np.maximum(actual, 1e-9))
    return float(np.mean(np.abs(ratio) <= np.log10(factor)))


def test_all():
    print("=" * 60)
    print("Article 2: Carbonate Rock-Type Permeability Modeling")
    print("=" * 60)

    phi, k, rrt = make_carbonate_dataset()
    swi = np.where(rrt == "grainy", RRT["grainy"]["swi"],
          np.where(rrt == "mixed",  RRT["mixed"]["swi"],
                                    RRT["muddy"]["swi"]))

    # Per-RRT FZI fit and prediction
    fzi_global = float(np.mean(fzi(k, phi)))
    k_global = k_from_fzi(phi, fzi_global)
    print(f"  Global FZI fit:    factor-of-2 hit = {factor_within(k_global, k):.2f}")

    print("  Per-RRT fits:")
    for name in RRT:
        mask = rrt == name
        f_hat = float(np.mean(fzi(k[mask], phi[mask])))
        k_hat = k_from_fzi(phi[mask], f_hat)
        rfn_hat = float(np.mean(lucia_rfn_from_swi(phi[mask], swi[mask])))
        k_lucia = lucia_k(phi[mask], rfn_hat)
        r35_hat = float(np.median(winland_r35(k[mask], phi[mask])))
        k_winl = winland_k(phi[mask], r35_hat)

        print(f"    {name:6s}  FZI={f_hat:5.2f}  RFN={rfn_hat:4.2f}  r35={r35_hat:5.2f} um")
        print(f"            within x2  FZI={factor_within(k_hat, k[mask]):.2f}"
              f"  Lucia={factor_within(k_lucia, k[mask]):.2f}"
              f"  Winland={factor_within(k_winl, k[mask]):.2f}")

    # Sanity: per-RRT FZI fits beat the global FZI fit
    per_rrt_score = []
    for name in RRT:
        mask = rrt == name
        f_hat = float(np.mean(fzi(k[mask], phi[mask])))
        per_rrt_score.append(factor_within(k_from_fzi(phi[mask], f_hat), k[mask]))
    assert np.mean(per_rrt_score) > factor_within(k_global, k), \
        "Per-RRT fit should outperform global FZI fit"
    print("  PASS")
    return {"global_x2": factor_within(k_global, k),
            "per_rrt_mean_x2": float(np.mean(per_rrt_score))}


if __name__ == "__main__":
    test_all()
