"""
Article 4: Deep-Learning-Based Automated Sedimentary Geometry
           Characterization From Borehole Images
Lefranc, Bayraktar, Kristensen, Driss, Le Nir, Marza, Kherroubi (2021)
DOI: 10.30632/PJV62N6-2021a4

An automated deep-learning workflow classifies sedimentary bedform geometries
from borehole images independent of well deviation.  Synthetic training
images are generated by drilling virtual wells through forward bedform models;
a planar surface intersecting the borehole appears as a sinusoid.  CNN
ensembles (CNN15 / ResNet60) classify the structures via a sliding window.

Implements:

  - Sinusoid model of a planar bed on an unrolled image            (R9)
        z(phi) = z0 - r*tan(dip) * cos(phi - phi0)
  - Least-squares sinusoid fit -> apparent dip & dip azimuth
  - Softmax                                                        (R5)
  - Categorical cross-entropy loss                                 (R6)
  - Classification accuracy                                        (R7)
  - The 4-level bedform classification hierarchy (Rubin 1987)

Note: the paper contains no equations (CNN architecture and the sinusoid-dip
relation are described in prose / figures).  The forms here are standard
reconstructions, flagged as such.  A full CNN is replaced by the analytic
sinusoid-fit core (the geometric heart of the method) plus the standard
classification primitives, so the module runs with numpy alone.
"""

import numpy as np

# 4-level bedform classification hierarchy (Rubin 1987 / Fig. 2)
SHAPE = ["2D", "3D"]                 # planform shape
TIME = ["inv", "var"]                # variability through time
CREST = ["T", "O", "L"]              # transverse / oblique / longitudinal
BEDFORM = ["PS", "SB"]               # planform sinuosity / superimposed bedforms


# ---------------------------------------------- R9: bed sinusoid --------

def bed_sinusoid(phi_deg, z0, radius, dip_deg, azimuth_deg):
    """Depth trace of a planar bed on an unrolled borehole image (R9).

    z(phi) = z0 - radius*tan(dip) * cos(phi - azimuth).
    Amplitude = radius*tan(dip); minimum (deepest) at the dip azimuth.
    """
    phi = np.radians(np.asarray(phi_deg, float))
    a = np.radians(azimuth_deg)
    return z0 - radius * np.tan(np.radians(dip_deg)) * np.cos(phi - a)


def fit_sinusoid(phi_deg, z, radius):
    """Least-squares fit z = z0 - A*cos(phi-phi0); return (dip_deg, azimuth_deg, z0).

    Linear in [1, cos phi, sin phi]: z = c0 + c1 cos + c2 sin, with
    amplitude A = sqrt(c1^2 + c2^2) and azimuth from atan2.
    """
    phi = np.radians(np.asarray(phi_deg, float))
    G = np.column_stack([np.ones_like(phi), np.cos(phi), np.sin(phi)])
    c, *_ = np.linalg.lstsq(G, np.asarray(z, float), rcond=None)
    c0, c1, c2 = c
    # z = c0 + c1 cos + c2 sin = c0 - A cos(phi - phi0)  =>  amplitude & phase
    amplitude = np.hypot(c1, c2)
    azimuth = np.degrees(np.arctan2(-c2, -c1)) % 360.0
    dip = np.degrees(np.arctan2(amplitude, radius))
    return float(dip), float(azimuth), float(c0)


# ---------------------------------------------- R5-R7: classifier -------

def softmax(z):
    """Softmax over the last axis (R5)."""
    z = np.asarray(z, float)
    z = z - z.max(axis=-1, keepdims=True)
    e = np.exp(z)
    return e / e.sum(axis=-1, keepdims=True)


def cross_entropy(probs, labels):
    """Mean categorical cross-entropy (R6).  labels = integer class indices."""
    probs = np.asarray(probs, float)
    idx = np.asarray(labels, int)
    p = probs[np.arange(len(idx)), idx]
    return float(-np.mean(np.log(np.clip(p, 1e-12, 1.0))))


def accuracy(probs, labels):
    """Top-1 classification accuracy (R7)."""
    pred = np.argmax(np.asarray(probs, float), axis=-1)
    return float(np.mean(pred == np.asarray(labels, int)))


def bedform_label(shape, time, crest, bedform):
    """Compose a hierarchical label, e.g. '3D_var_T_PS'."""
    return f"{SHAPE[shape]}_{TIME[time]}_{CREST[crest]}_{BEDFORM[bedform]}"


# ---------------------------------------------- tests --------------

def test_all():
    print("=" * 60)
    print("Article 4: DL Sedimentary Geometry From Borehole Images")
    print("=" * 60)

    # Synthesize a planar bed and recover its dip & azimuth from the sinusoid
    phi = np.arange(0, 360, 5.0)             # azimuth samples around borehole
    radius = 4.25                             # 8.5-in borehole radius (in)
    dip_true, az_true = 30.0, 120.0
    z = bed_sinusoid(phi, z0=100.0, radius=radius,
                     dip_deg=dip_true, azimuth_deg=az_true)

    dip, az, z0 = fit_sinusoid(phi, z, radius)
    print(f"  fitted dip / azimuth   = {dip:.2f} deg / {az:.1f} deg")
    print(f"  true   dip / azimuth   = {dip_true:.2f} deg / {az_true:.1f} deg")
    assert abs(dip - dip_true) < 0.5
    assert min(abs(az - az_true), abs(az - az_true - 360)) < 1.0

    # Fit is robust to image noise
    rng = np.random.default_rng(0)
    zn = z + rng.normal(0, 0.05, z.size)
    dip_n, az_n, _ = fit_sinusoid(phi, zn, radius)
    assert abs(dip_n - dip_true) < 2.0

    # Classification primitives
    logits = np.array([[2.0, 0.5, 0.1], [0.2, 0.3, 3.0], [1.0, 0.9, 0.8]])
    probs = softmax(logits)
    assert np.allclose(probs.sum(axis=1), 1.0)
    labels = [0, 2, 0]
    acc = accuracy(probs, labels)
    ce = cross_entropy(probs, labels)
    print(f"  softmax accuracy / CE  = {acc:.2f} / {ce:.3f}")
    assert acc == 1.0 and ce > 0.0

    lbl = bedform_label(1, 1, 0, 0)
    print(f"  example bedform label  = {lbl}")
    assert lbl == "3D_var_T_PS"
    print("  PASS")
    return {"dip": dip, "azimuth": az, "accuracy": acc, "label": lbl}


if __name__ == "__main__":
    test_all()
